version: '3'
services:
  proxy:
    image: nginx   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keys:/etc/nginx/keys
    networks:
      - internal
    ports:
      - 80:80
      - 443:443
  node:
    build: backend/nodejs
    networks:
      - internal
  frontend:
    build: frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
networks:
  internal:
